version: '2'

services:

  # MySql
  mysqlDB:
    image: "mysql:5.7"
    env_file:
      - '.env'
    container_name: flask_app_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./datadir/:/var/lib/mysql
    ports:
      - "3306:3306"
  
  # phpMyAdmin
  phpmyadmin:
    depends_on:
      - mysqlDB
    image: phpmyadmin/phpmyadmin
    env_file:
      - '.env'
    container_name: flask_app_phpMyAdmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysqlDB

  # Redis
  redis:
    image: 'redis:5'
    env_file:
      - '.env'
    container_name: flask_app_redis
    command: redis-server --requirepass secretPassword
    volumes:
      - './redis:/var/lib/redis/data'
    ports:
      - '6379:6379'
  
  # App
  app:
    env_file:
      - '.env'
    build: .
    container_name: flask_app
    command: >
      gunicorn -b 0.0.0.0:5000
        --access-logfile -
        --reload
        "app:create_app()"
    depends_on:
      - mysqlDB
    links:
      - "mysqlDB:localhost"
    ports:
      - "5000:5000"
    # bind our project directory to the container WORKDIR for tracking changes
    volumes:
      - '.:/flask_app'

  # Celery
  celery:
    env_file:
      - '.env'
    build: .
    container_name: flask_app_celery
    command: celery worker -l info -A tasks.tasks
    volumes:
      - '.:/flask_app'



